import Link from "next/link";
import { PONS_V2_FACTORY } from "@/lib/chain";

export const metadata = { title: "Documentation" };

export default function DocsPage() {
  return <main className="shell page-shell docs-page"><aside className="docs-nav"><strong>Documentation</strong><a href="#product">Product states</a><a href="#games">Game runtime</a><a href="#pons">pons integration</a><a href="#scores">Scores</a><a href="#credits">Free credit</a><a href="#security">Security</a><Link href="/create">Open studio ↗</Link></aside><article className="docs-content"><span className="eyebrow">Phase 1 · production surface</span><h1>Game Studio for pons</h1><p className="lead">An independent interface for generating controlled HTML5 games and launching their tokens through the documented pons V2 factory on Robinhood Chain.</p>
    <section id="product"><h2>Product states</h2><p>A project begins as a private draft. For signed-in creators, AI directs a strictly validated blueprint; a local deterministic generator remains the safe fallback. The resulting preview is frozen before any wallet prompt appears. The public page is published only after a successful transaction has been decoded and matched to the frozen intent.</p><div className="state-row"><span>draft</span><i>→</i><span>preview ready</span><i>→</i><span>awaiting signature</span><i>→</i><span>confirming</span><i>→</i><span>live</span></div><p>Failures preserve the game and release any reserved free-launch credit. Demo pages always say demo and never display simulated market values.</p></section>
    <section id="games"><h2>Controlled game runtime</h2><p>Phase 1 supports runner, flappy-style, and top-down shooter engines. AI prompt interpretation produces validated JSON for story, palette, forms, physics, spawn pacing, collectibles, enemy behavior, instructions, and sound. Models never provide executable HTML or JavaScript; Pons builds the phone-friendly HTML5 game inside its trusted sandbox.</p><pre><code>{`configHash = sha256(canonicalConfig)\nmanifestHash = sha256(frozenDocumentHtml)`}</code></pre><p>The separately hash-addressed token image and both game hashes are retained with the draft. Published game documents are immutable. The runtime supports keyboard, pointer, and touch controls plus pause, restart, mute, and fullscreen.</p></section>
    <section id="pons"><h2>Verified pons integration</h2><p>No private pons API sits in the trust path. The launch surface reads and writes the public V2 contracts with Viem.</p><dl className="docs-facts"><div><dt>Chain</dt><dd>Robinhood Chain · 4663</dd></div><div><dt>Factory</dt><dd><code>{PONS_V2_FACTORY}</code></dd></div><div><dt>Pair</dt><dd>Native ETH for Phase 1</dd></div><div><dt>Trust source</dt><dd><a href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">Official V2 docs ↗</a></dd></div></dl><p>Before each launch the server reads <code>canLaunch</code>, <code>launchFee</code>, enabled configs, the maximum creator tax, and <code>previewLaunchEconomics</code>. The user wallet signs <code>launchToken</code>. Confirmation requires the canonical <code>TokenLaunched</code> event and a matching factory record.</p><div className="risk-box"><b>Contract notice</b><p>The official V2 documentation says audits are still in progress. A runtime kill switch can pause new launch preparation without affecting saved games.</p></div></section>
    <section id="scores"><h2>Scores and replay checks</h2><p>Only signed-in creators with a verified wallet receive a short-lived run session. Submission includes a bounded event log. The server checks duration, ordering, input rate, category-specific score ceilings, and a replay hash before an entry reaches the leaderboard.</p></section>
    <section id="credits"><h2>Free first launch</h2><p>Exactly one credit is tied to the immutable X account ID, and a wallet can be used for only one reserved or consumed free credit. pons has no documented gasless launch path. Phase 1 therefore supports a post-confirmation launch-fee reimbursement when the owner-funded sponsor is enabled. Until funded, the credit stays available and the UI does not call a paid launch free.</p></section>
    <section id="security"><h2>Security model</h2><ul><li>HTTP-only OAuth session and immutable X identity</li><li>EIP-4361-style expiring wallet challenge</li><li>Strict image magic-byte and size checks</li><li>Sandboxed, networkless game iframe</li><li>On-chain intent and receipt verification</li><li>Rate limits, idempotency keys, database locks, and audit logs</li><li>No creator private key or automatic transaction approval</li></ul></section>
  </article></main>;
}
