import type { Metadata } from "next";
import { headers } from "next/headers";
import "@fontsource-variable/inter";
import "@fontsource-variable/manrope";
import "@fontsource/instrument-serif";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: { default: "gamepad.markets", template: "%s · gamepad.markets" },
  description: "Create a playable game, launch its token through pons, and let the market play on Robinhood Chain.",
  icons: { icon: "/gamepad-logo.png", apple: "/gamepad-logo.png" },
};

const RAILWAY_ORIGIN = "https://gamepad.markets";

function configuredAppOrigin() {
  try {
    return new URL(process.env.APP_URL || process.env.NEXTAUTH_URL || RAILWAY_ORIGIN).origin;
  } catch {
    return RAILWAY_ORIGIN;
  }
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Reading request headers opts every page into dynamic rendering so the CSP
  // nonce generated by middleware is present on Next's framework scripts.
  await headers();
  return <html lang="en"><body><Providers appUrl={configuredAppOrigin()}><Header /><div className="site-content">{children}</div><Footer /></Providers></body></html>;
}
