import type { Metadata } from "next";
import { headers } from "next/headers";
import "@fontsource-variable/inter";
import "./globals.css";
import { Providers } from "@/components/providers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: { default: "pons game studio", template: "%s · pons game studio" },
  description: "Describe a game, generate a playable HTML5 build, and launch its token through pons on Robinhood Chain.",
  icons: { icon: "/favicon.svg" },
};

const RAILWAY_ORIGIN = "https://pons-game-studio-web-production.up.railway.app";

function configuredAppOrigin() {
  try {
    return new URL(process.env.APP_URL || process.env.NEXTAUTH_URL || RAILWAY_ORIGIN).origin;
  } catch {
    return RAILWAY_ORIGIN;
  }
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Reading request headers opts every page into dynamic rendering so the CSP
  // nonce generated by middleware is present on Next's framework scripts.
  await headers();
  return <html lang="en"><body><Providers appUrl={configuredAppOrigin()}><Header /><div className="site-content">{children}</div><Footer /></Providers></body></html>;
}
