import Link from "next/link";
import { PromptHero } from "@/components/prompt-hero";
import { GameFrame } from "@/components/game-frame";
import { exploreGames } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function HomePage() {
  const games = await exploreGames();
  const featured = games[0];
  return <main>
    <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> Built for pons on Robinhood Chain</div><h1>Describe it.<br /><span>Launch it.</span> Play it.</h1><p>Turn one prompt into a real, phone-ready HTML5 game. Keep the playable build beside its token, then let the community compete for the high score.</p><div className="hero-actions"><Link className="button button-primary" href="/create">Create a game</Link><Link className="button button-quiet" href="/explore">Explore games</Link></div><div className="signup-note"><span>First launch credit</span><p>Sign in with X, verify one wallet, and keep exactly one launch entitlement.</p></div></div><div className="hero-console"><PromptHero /><div className="console-foot"><span>Controlled templates</span><i /><span>No arbitrary code</span><i /><span>Wallet-signed launch</span></div></div></section>
    <section className="flow-strip"><div className="shell flow-row">{["Prompt","Game","Token","Play","Compete"].map((item, index) => <div key={item}><span>{String(index + 1).padStart(2,"0")}</span><b>{item}</b>{index < 4 && <em>→</em>}</div>)}</div></section>
    <section className="product-section shell"><div className="section-intro"><div><span className="eyebrow">One prompt, real play</span><h2>The game exists before the token does.</h2></div><p>Test every jump, tap, and shot. The launch button appears only after a version is frozen and the current pons terms are read on-chain.</p></div><div className="feature-grid"><article className="feature-card accent-card"><span className="feature-number">01</span><div className="mini-stage"><i className="runner" /><i className="obstacle" /><i className="coin" /></div><h3>Generate a controlled game</h3><p>Your prompt configures one of three audited surfaces: runner, flappy-style, or top-down shooter.</p></article><article className="feature-card"><span className="feature-number">02</span><div className="token-orbit"><span>$</span><i /><i /><i /></div><h3>Launch through pons</h3><p>Your connected wallet signs the official V2 factory call. We independently verify the receipt before publishing.</p></article><article className="feature-card"><span className="feature-number">03</span><div className="score-mini"><b>12,480</b><span>verified score</span><i style={{width:"82%"}} /><i style={{width:"64%"}} /><i style={{width:"46%"}} /></div><h3>Play for the board</h3><p>Runs carry a server session and event log. Impossible scores never reach the public leaderboard.</p></article></div></section>
    {featured && <section className="featured-section"><div className="shell featured-grid"><div className="featured-copy"><span className="eyebrow">Playable now · {featured.status.toLowerCase()}</span><h2>{featured.name}</h2><p>{featured.description}</p><dl><div><dt>Engine</dt><dd>{featured.category.toLowerCase()}</dd></div><div><dt>Token</dt><dd>{featured.tokenAddress ? `$${featured.ticker}` : "Not launched"}</dd></div><div><dt>Build</dt><dd>Immutable v1</dd></div></dl><Link className="button button-quiet" href={`/game/${featured.tokenAddress || featured.slug}`}>Open full game page</Link></div><GameFrame title={featured.name} publicId={featured.tokenAddress || featured.slug} versionId={featured.versionId || "demo"} /></div></section>}
    <section className="final-cta shell"><div><span className="eyebrow">Start with the game</span><h2>What will your token play like?</h2></div><Link className="button button-primary" href="/create">Create the first version →</Link></section>
  </main>;
}
